package com.yuchengdai.crm.settings.domain;

public class DictionaryType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_type.code
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_type.name
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_type.description
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_type.code
     *
     * @return the value of tbl_dictionary_type.code
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_type.code
     *
     * @param code the value for tbl_dictionary_type.code
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_type.name
     *
     * @return the value of tbl_dictionary_type.name
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_type.name
     *
     * @param name the value for tbl_dictionary_type.name
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_type.description
     *
     * @return the value of tbl_dictionary_type.description
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_type.description
     *
     * @param description the value for tbl_dictionary_type.description
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}