package com.yuchengdai.crm.settings.domain;

public class DictionaryValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.id
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.value
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.text
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.order_no
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.type_code
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    private String typeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.id
     *
     * @return the value of tbl_dictionary_value.id
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.id
     *
     * @param id the value for tbl_dictionary_value.id
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.value
     *
     * @return the value of tbl_dictionary_value.value
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.value
     *
     * @param value the value for tbl_dictionary_value.value
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.text
     *
     * @return the value of tbl_dictionary_value.text
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.text
     *
     * @param text the value for tbl_dictionary_value.text
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.order_no
     *
     * @return the value of tbl_dictionary_value.order_no
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.order_no
     *
     * @param orderNo the value for tbl_dictionary_value.order_no
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.type_code
     *
     * @return the value of tbl_dictionary_value.type_code
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.type_code
     *
     * @param typeCode the value for tbl_dictionary_value.type_code
     *
     * @mbg.generated Sun Mar 08 16:31:05 CST 2017
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }
}