package com.yuchengdai.crm.settings.mapper;

import com.yuchengdai.crm.settings.domain.User;

import java.util.List;
import java.util.Map;


public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Thu Mar 05 22:12:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Thu Mar 05 22:12:56 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Thu Mar 05 22:12:56 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Thu Mar 05 22:12:56 CST 2017
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Thu Mar 05 22:12:56 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Thu Mar 05 22:12:56 CST 2017
     */
    int updateByPrimaryKey(User record);


    //通过loginAct和loginPwd查询用户
    User selectUserByActPwd(Map<String, Object> map);

    //通过loginPwd查询用户带上Id
    User selectUserByPwdId(Map<String, Object> map);

    //通过id更新用户信息
    int updateUserById(User user);

    //获取所有人员信息
    List<User> selectAllUsers();
}